name: ArisClear
version: 1.0
main: me.aris.arisclear.ArisClear
api-version: 1.20
author: VennLMAO
folia-supported: true
softdepend: [PlaceholderAPI]
commands:
  arisclear:
    description: Quan tri ArisClear
    usage: /arisclear clear
    permission: arisclear.admin
